name: Build, pack and push HorusStudio.Maui.MaterialDesignControls NuGet package

on:
  push:
    branches: [ "feature/pipelines" ] # branches: [ "master" ]

env:
  SLN_FILE_PATH: 'HorusStudio.Maui.MaterialDesignControls.sln'
  CSPROJ_FILE_PATH: 'src/HorusStudio.Maui.MaterialDesignControls/HorusStudio.Maui.MaterialDesignControls.csproj'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        include-prerelease: true

    - name: Install MAUI workloads
      run: |
        echo "📦 Installing MAUI workloads..."
        dotnet workload install maui
        dotnet workload restore
        echo "✅ MAUI workloads installed successfully!"

    - name: Restore dependencies
      run: |
        echo "📦 Restoring dependencies..."
        dotnet restore ${{ env.SLN_FILE_PATH }}
        echo "✅ Dependencies restored successfully!"

    - name: Build solution
      run: |
        echo "📦 Building solution..."
        dotnet build ${{ env.CSPROJ_FILE_PATH }} -c Release --no-restore
        echo "✅ Solution built successfully!"
      
    - name: Pack NuGet package
      run: |
        echo "📦 Packaging NuGet package..."
        dotnet pack ${{ env.CSPROJ_FILE_PATH }} -c Release -o ./artifacts --no-build
        echo "✅ NuGet package packed successfully!"

    - name: Publish NuGet package
      run: |
        echo "📦 Publishing NuGet package..."
        # echo "📦 TESTING..."
        echo "✅ NuGet package published successfully!"

# dotnet nuget push "./artifacts/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate